---
author: DixieCyanide
main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
depend:
  - FastAsyncWorldEdit
softdepend:
  - SchematicBrush
commands:
  wood:
    description: Creates a forest/wood in your selection from schematics
    usage: /wood {schematic(s)} [!]{block ID(s)} [flags -includeAir,-dontRotate,-r:x]
    aliases:
      - /wood
      - /w
    permission: btemoreenhanced.region.wood
  btemoreenhanced-reload:
    description: Reload config
    usage: /btemoreenhanced-reload
    permission: btemoreenhanced.reload
  treebrush:
    description: Easy to use brush specifically for trees on top of //schbr (Schematic Brush Plugin)
    usage: /treebrush {type} [size] [thickness]
    aliases:
      - tbr
      - treebr
      - /tbr
  /dell:
    description: Deletes last [num] point(s) in (currently poly2d only) selection
    usage: //dell [num]
    aliases:
      - dell
      - dellast
      - /dellast
    permission: btemoreenhanced.selection.dellast
  /delp:
    description: Deletes the [num] point in (currently poly2d only) selection
    usage: //delp [num]
    aliases:
      - delp
      - delpoint
      - /delpoint
    permission: btemoreenhanced.selection.delpoint
permissions:
  btemoreenhanced.*:
    description: Wildcard permission
    children:
      btemoreenhanced.region: true
      btemoreenhanced.region.wood: true
      btemoreenhanced.reload: true
      btemoreenhanced.selection: true
      btemoreenhanced.selection.dellast: true
      btemoreenhanced.selection.delpoint: true
  btemoreenhanced.admin.*:
    description: All "admin" perms
    children:
      btemoreenhanced.admin.reload: true
      btemoreenhanced.admin.allschematics: true
  btemoreenhanced.admin.reload:
    description: Reload config
  btemoreenhanced.admin.allschematics:
    description: Allows people to use all files in schematics folder
  btemoreenhanced.region.*:
    description: All region commands
    children:
      btemoreenhanced.region.wood: true
  btemoreenhanced.region.wood:
    description: Allows usage of /wood
  btemoreenhanced.selection.*:
    description: Allows usage of all selection related commands
    children:
      btemoreenhanced.selection.dellast: true
      btemoreenhanced.selection.delpoint: true
  btemoreenhanced.selection.dellast:
    description: Allows usage of //dell
  btemoreenhanced.selection.delpoint:
    description: Allows usage of //delp
