---
author: VapoR
main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
depend:
  - WorldEdit
commands:
  wood:
    description: Creates a forest/wood in your selection from schematics
    usage: /wood <schematic(s)> [!]<blockID(s)> [flags -includeAir,-dontRotate,-r:x]
    aliases:
      - /wood
      - /w
    permission: bteenhanced.wood
  bteenhanced-reload:
    description: Reload config
    usage: /bteenhanced-reload
    permission: bteenhanced.reload
  /dell:
    description: Deletes last [num] point(s) in (currently poly2d only) selection
    usage: //dell [num]
    aliases:
      - dell
      - dellast
      - /dellast
    permission: bteenhanced.selection.dellast
  /delp:
    description: Deletes the [num] point in (currently poly2d only) selection
    usage: //delp [num]
    aliases:
      - delp
      - delpoint
      - /delpoint
    permission: bteenhanced.selection.delpoint
permissions:
  bteenhanced.*:
    description: Wildcard permission
    default: op
    children:
      bteenhanced.wood: true
      bteenhanced.wood.all: true
      bteenhanced.reload: true
      bteenhanced.selection: true
      bteenhanced.selection.dellast: true
      bteenhanced.selection.delpoint: true
  bteenhanced.reload:
    description: Reload config
    default: op
  bteenhanced.wood.*:
    description: Allows usage of /wood
    default: op
    children:
      bteenhanced.wood.all: true
  bteenhanced.wood.all:
    description: Allows people to use all files in schematics folder with *
    default: op
  bteenhanced.selection.*:
    description: Allows usage of all selection related commands
    default: op
    children:
      bteenhanced.selection.dellast: true
      bteenhanced.selection.delpoint: true
  bteenhanced.selection.dellast:
    description: Allows usage of //dell
    default: op
  bteenhanced.selection.delpoint:
    description: Allows usage of //delp
    default: op
