---
author: VapoR
main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
depend:
  - WorldEdit
commands:
  wood:
    description: Creates a forest/wood in your selection from schematics
    usage: /wood {schematic(s)} [!]{block ID(s)} [flags -includeAir,-dontRotate,-r:x]
    aliases:
      - /wood
      - /w
    permission: bteenhanced.region.wood
  bteenhanced-reload:
    description: Reload config
    usage: /bteenhanced-reload
    permission: bteenhanced.reload
  treebrush:
    description: Easy to use brush specifically for trees on top of //schbr (Schematic Brush Plugin)
    usage: /treebrush {type} [size] [thickness]
    aliases:
      - tbr
      - treebr
      - /tbr
  bwall:
    description: Creates walls around a selection
    usage: /bwall {pattern}
    aliases:
      - /bwall
    permission: bteenhanced.region.wall
  /dell:
    description: Deletes last [num] point(s) in (currently poly2d only) selection
    usage: //dell [num]
    aliases:
      - dell
      - dellast
      - /dellast
    permission: bteenhanced.selection.dellast
  /delp:
    description: Deletes the [num] point in (currently poly2d only) selection
    usage: //delp [num]
    aliases:
      - delp
      - delpoint
      - /delpoint
    permission: bteenhanced.selection.delpoint
permissions:
  bteenhanced.*:
    description: Wildcard permission
    children:
      bteenhanced.region: true
      bteenhanced.region.wood: true
      bteenhanced.reload: true
      bteenhanced.selection: true
      bteenhanced.selection.dellast: true
      bteenhanced.selection.delpoint: true
  bteenhanced.admin.*:
    description: All "admin" perms
    children:
      bteenhanced.admin.reload: true
      bteenhanced.admin.allschematics: true
  bteenhanced.admin.reload:
    description: Reload config
  bteenhanced.admin.allschematics:
    description: Allows people to use all files in schematics folder
  bteenhanced.region.*:
    description: All region commands
    children:
      bteenhanced.region.wood: true
      bteenhanced.region.wall: true
  bteenhanced.region.wood:
    description: Allows usage of /wood
  bteenhanced.region.wall:
    description: Allows usage of /bwall
  bteenhanced.selection.*:
    description: Allows usage of all selection related commands
    children:
      bteenhanced.selection.dellast: true
      bteenhanced.selection.delpoint: true
  bteenhanced.selection.dellast:
    description: Allows usage of //dell
  bteenhanced.selection.delpoint:
    description: Allows usage of //delp
